version: '3.8'

volumes:
    mysql:
        driver: local

networks:
    laravel:
        driver: bridge

services:
    adminer:
        image: adminer
        ports:
            - "8081:8080"
        restart: always
        networks:
            - laravel
    mysql:
        image: "mysql:8.0"
        ports:
            - "33060:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - laravel
    pgsql:
        image: "postgres:14"
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: lara
        volumes:
            - mysql:/var/lib/postgresql
        networks:
            - laravel
    php:
        build:
            context: .docker/php # ~.docker/php/Dockerfile
        ports:
            - "8080:80"
        restart: always
        volumes:
            -   .:/var/www/html
        networks:
            - laravel
